### ISSUE TITLE
:children_crossing: :recycle: enable apply and prepare of module task to return and receive json Values

### ISSUE THREAD

**Issue by Spiegie** [linkdd/tricorder#28]
The apply function expects a string right now. 
It could be desirable that it can receive json-values or other values to reduce complexity.

**Comment by linkdd** [comment]
This is already possible. See the trait `GenericTask` in [src/prelude/tasks/task.rs](https://github.com/linkdd/tricorder/blob/main/src/prelude/tasks/task.rs).

The current tasks implement `GenericTask<String>` but nothing prevents you from implementing `GenericTask<serde_json::Value>`.

I'm closing this issue :)
